### ISSUE TITLE
README.md suggests quartermaster is fully operational after setting up IntelliJ support

### ISSUE THREAD

**Issue by tinne** [reflectoring/infiniboard#11]
Running `$ ./gradlew -t classes` after cloning repo (as README.md suggests) leads to errors since infiniboard-app has no valid npm configuration.

(Do not know why, :infiniboard-app:node-setup seems to be inserted too late in the dependency hierarchy and is never called.)

`$ (cd infiniboard-app && npm install)` beforehand fixes the issue.

Also, please add that a Python in [2.5, 3.0) must be available on the system and that gulp-cli should have been installed globally (on npm).

**Comment by matthiasbalke** [comment]
were do we use python?

**Comment by tinne** [comment]
The answer is [node-gyp:](https://www.npmjs.com/package/node-gyp)

Put a python 3+ in your CLASSPATH, run npm and find out...: running `npm install` with python 3.5.1 in PATH gives the following errors while python 2.7.11 works fine, since 

```log
> bufferutil@1.2.1 install D:\Projekte\infiniboard\reflectoring\infiniboard\infiniboard-app\node_modules\bufferutil
> node-gyp rebuild

D:\Projekte\infiniboard\reflectoring\infiniboard\infiniboard-app\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Program Files\Python 3.5\python.EXE" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projekte\infiniboard\reflectoring\infiniboard\infiniboard-app\node_modules\bufferutil
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install D:\Projekte\infiniboard\reflectoring\infiniboard\infiniboard-app\node_modules\utf-8-validate
> node-gyp rebuild

D:\Projekte\infiniboard\reflectoring\infiniboard\infiniboard-app\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Program Files\Python 3.5\python.EXE" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projekte\infiniboard\reflectoring\infiniboard\infiniboard-app\node_modules\utf-8-validate
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
```

**Comment by matthiasbalke** [comment]
ATM we don't use building native packages using node-gyp. So python 2.7 and others are not needed.
More infos: https://www.npmjs.com/package/node-gyp

**Comment by tinne** [comment]
You told me so. Question is, can users silently ignore the errors irrespectively if they have a python in their PATHs, and with whatever version?

**Comment by matthiasbalke** [comment]
Actually that's a good question. If the user happens to have all packages to build with node-gyp the build differs. I don't how locally build packages affect our build.

@acetous do you have any experience with node-gyp?

**Comment by matthiasbalke** [comment]
As far as I know our build system circle.ci builds node modules with `node-gyp` so we should have a fair chance of detecting problems regarding this difference.
